/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as LayoutProfileAccountIdRouteImport } from './routes/_layout/profile/$accountId'
import { Route as LayoutAuthenticatedShopRouteImport } from './routes/_layout/_authenticated/shop'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedCheckoutSuccessRouteImport } from './routes/_layout/_authenticated/checkout-success'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProfileAccountIdRoute = LayoutProfileAccountIdRouteImport.update({
  id: '/profile/$accountId',
  path: '/profile/$accountId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedShopRoute = LayoutAuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedCheckoutSuccessRoute =
  LayoutAuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout-success',
    path: '/checkout-success',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/checkout-success': typeof LayoutAuthenticatedCheckoutSuccessRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/shop': typeof LayoutAuthenticatedShopRoute
  '/profile/$accountId': typeof LayoutProfileAccountIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/checkout-success': typeof LayoutAuthenticatedCheckoutSuccessRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/shop': typeof LayoutAuthenticatedShopRoute
  '/profile/$accountId': typeof LayoutProfileAccountIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/checkout-success': typeof LayoutAuthenticatedCheckoutSuccessRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/_layout/_authenticated/shop': typeof LayoutAuthenticatedShopRoute
  '/_layout/profile/$accountId': typeof LayoutProfileAccountIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/checkout-success'
    | '/dashboard'
    | '/shop'
    | '/profile/$accountId'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/checkout-success'
    | '/dashboard'
    | '/shop'
    | '/profile/$accountId'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/_authenticated'
    | '/_layout/'
    | '/_layout/_authenticated/checkout-success'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/shop'
    | '/_layout/profile/$accountId'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/profile/$accountId': {
      id: '/_layout/profile/$accountId'
      path: '/profile/$accountId'
      fullPath: '/profile/$accountId'
      preLoaderRoute: typeof LayoutProfileAccountIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/shop': {
      id: '/_layout/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof LayoutAuthenticatedShopRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/checkout-success': {
      id: '/_layout/_authenticated/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof LayoutAuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedCheckoutSuccessRoute: typeof LayoutAuthenticatedCheckoutSuccessRoute
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRoute
  LayoutAuthenticatedShopRoute: typeof LayoutAuthenticatedShopRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedCheckoutSuccessRoute:
    LayoutAuthenticatedCheckoutSuccessRoute,
  LayoutAuthenticatedDashboardRoute: LayoutAuthenticatedDashboardRoute,
  LayoutAuthenticatedShopRoute: LayoutAuthenticatedShopRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileAccountIdRoute: typeof LayoutProfileAccountIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileAccountIdRoute: LayoutProfileAccountIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
